project:
  type: website
  output-dir: docs

website:
  title: "Sunny Liang Tan"
  site-url: "https://sunnyliangtan.github.io"
  favicon: logo.png
  navbar:
    left:
      - href: about.qmd
        text: About
      - href: research/index.qmd
        text: Research
      - href: Sunny_Liang_Tan_MIT_Style_English_Job_Market_CV.pdf
        text: CV

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    include-in-header:
      - text: |
          <meta name="google-site-verification" content="dRyMp2N5NDEAw_7zG_WNqNOaaHUFy0-oAqpIgaUtp-4" />

editor:
  render-on-save: true
